- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimeLinePanel.kt
> Timeline: Fix time maker position and direction

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/DrawScopeUtils.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimeLineViewStyle.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineEventView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineMinMaxValueView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelinePercentageView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineStateView.kt
Improved look and feel for diagrams and some basic functions moved to dedicated file
> Timeline views refactoring

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/DrawScopeUtils.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimeRuler.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineEventView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineMinMaxValueView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelinePercentageView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineStateView.kt
Better series layouts were implemented and series business logic was hidden from Timeline views.
> Timeline view layout improvements

- composeApp/build.gradle.kts
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/ui/ImageButton.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/ui/ToggleImageButton.kt
- gradle/libs.versions.toml
Update compose plugin 1.5.11 -> 1.6.2
> Update compose plugin

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/Cell.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogRow.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsPanel.kt
Update logs rows layout and fix #8
> Update rows layout

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsToolbar.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/ui/AutoCompleteEditText.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/ui/MainWindow.kt
> Autocomplete is added for search edittext

- composeApp/src/commonTest/kotlin/ExtractPatternRegexTest.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/EditTimelineFilterDialog.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/TimelineFilter.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/ui/CustomEditText.kt
> Timeline filter dialog improvements

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/EditTimelineFilterDialog.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/ExtractorChecker.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/TimelineFilter.kt
> Timelinefilter testclause

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
Now we can use " F ", " E " or " W " etc as part of search to match log types
> Use LogTypeIndicator as part of Payload for search

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LazyScrollable.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsListPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/RowContextMenu.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/SearchResultsPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/ui/MainWindow.kt
> Remove logs from Context menu

- composeApp/build.gradle.kts
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LazyScrollable.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/model/LogMessage.kt
- gradle/libs.versions.toml
> LazyScrollable fixes

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/infopanel/DLTSimplifiedLogInfoView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/infopanel/LogPreviewPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/insights/InsightsRepository.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/insights/LogInsight.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/insights/LogInsightRule.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/ui/MainWindow.kt
- composeApp/src/desktopMain/kotlin/main.kt
Describe meaning of logs and provide insights
> Logs: Insights

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/graph/DrawScopeUtils.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/graph/TimelineEventView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/graph/TimelineMinMaxValueView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/graph/TimelinePercentageView.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/graph/TimelineStateView.kt
Sometimes when labels are too long the text is cut
> Timeline: measure text

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimeLinePanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/TimelineFilter.kt
> Timeline: Store timeline entries and highlight in maps

- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/ExtractPatternRegexTest.kt
- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/timeline/extractors/DurationEntriesExtractorTest.kt
- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/timeline/extractors/EventEntriesExtractorTest.kt
- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/timeline/extractors/MinMaxEntriesExtractorTest.kt
- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/timeline/extractors/PercentageEntriesExtractorTest.kt
- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/timeline/extractors/SingleStateEntriesExtractorTest.kt
- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/timeline/extractors/StateEntriesExtractorTest.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimeLinePanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/TimelineViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/ExtractorChecker.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/TimelineFilter.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/TimelineFiltersDialog.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/edit/EditTimelineFilterDialog.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/edit/EditTimelineFilterExtractPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/edit/EditTimelineFilterFilterPanel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/edit/EditTimelineFilterViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/extractors/DurationEntriesExtractor.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/extractors/EntriesExtractor.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/extractors/EventEntriesExtractor.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/extractors/MinMaxEntriesExtractor.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/extractors/PercentageEntriesExtractor.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/extractors/SingleStateEntriesExtractor.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/extractors/StateEntriesExtractor.kt
Breaking changes: Timeline extraction was rewritten to support more type.
> Timeline ExtractionType refactoring

- composeApp/build.gradle.kts
- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/timeline/filters/TimelineFiltersLoadingTest.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/colorfilters/ColorFilterManager.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/filtering/FilterCriteria.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/preferences/Preferences.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/TimeLineFilterManager.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/filters/TimelineFilter.kt
- gradle/libs.versions.toml
> Migrate from GSON to Kotlinx.Serialization

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/graph/DrawScopeUtils.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/timeline/graph/TimelineStateView.kt
Draw vertical lines with dashes.
1. Fixed wrong state transition for StateView
Before 
After
2. Draw vertical lines with dashes
> Fix wrong state transition for StateView

- composeApp/src/commonTest/kotlin/com/alekso/dltstudio/tests/logs/colorfilters/ColorFiltersLoadingTest.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/logs/colorfilters/ColorFilterManager.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/utils/ColorSerializer.kt
To avoid compatibility issues - serialize Color as ARGB hex string.
> Serialize Color as argb hex string for compatibility.

- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/DependencyManager.kt
- composeApp/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/PluginManager.kt
- pluginDeviceAnalyze/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/deviceplugin/DeviceAnalyzePlugin.kt
- pluginFilesViewer/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/filesviewer/FilesPlugin.kt
- pluginFilesViewer/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/filesviewer/FilesViewModel.kt
- plugins/src/commonMain/kotlin/com/alekso/dltstudio/plugins/DLTStudioPlugin.kt
- plugins/src/commonMain/kotlin/com/alekso/dltstudio/plugins/PluginPanel.kt
Initialize plugins with dependencies
> Refine plugins contract

- plugins/files-viewer/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/filesviewer/FilesPanel.kt
- plugins/files-viewer/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/filesviewer/FilesPlugin.kt
- plugins/files-viewer/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/filesviewer/FilesViewModel.kt
- ui-components/src/desktopMain/kotlin/com/alekso/dltstudio/uicomponents/dialogs/FileDialog.kt
Fixes bug with saving files dialog in FilesPanel
> New FileDialog

- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/logs/MessagesRepositoryImpl.kt
Fixes multiple search when fast clicking Search button
> Make searchMessages cancellation friendly

- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsPanel.kt
- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/logs/LogsPlugin.kt
- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/logs/MessagesRepositoryImpl.kt
- model-contract/src/commonMain/kotlin/com/alekso/dltstudio/model/contract/LogMessage.kt
- plugins/contract/src/commonMain/kotlin/com/alekso/dltstudio/plugins/contract/MessagesRepository.kt
- plugins/manager/src/commonTest/kotlin/com/alekso/dltstudio/plugins/LoadingPluginTest.kt
Fixes preview plugins update when commenting a message.
> Log selection via MessagesRepository

- plugins/manager/src/commonMain/kotlin/com/alekso/dltstudio/plugins/manager/PluginManager.kt
Do not fail loading plugins if a plugin init has failed.
> Try catch plugin init error

- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/Menu.kt
- desktop-app/src/desktopMain/kotlin/main.kt
- ui-components/src/desktopMain/kotlin/com/alekso/dltstudio/uicomponents/dialogs/FileChooserDialog.kt
Replace FileChooserDialog with FileDialog
> FileDialog for menu

- plugins/diagram-timeline/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/diagramtimeline/TimeLinePanel.kt
- plugins/diagram-timeline/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/diagramtimeline/TimeRuler.kt
Hide debug information by debug flag
> Hide timeline debug information

- desktop-app/build.gradle.kts
- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/MainViewModel.kt
- desktop-app/src/desktopMain/kotlin/com/alekso/dltstudio/logs/MessagesRepositoryImpl.kt
- extraction/build.gradle.kts
- extraction/src/commonMain/kotlin/com/alekso/dltstudio/extraction/ForeachWithProgress.kt
- extraction/src/commonMain/kotlin/com/alekso/dltstudio/extraction/ForeachWithProgressParallel.kt
- extraction/src/commonMain/kotlin/com/alekso/dltstudio/extraction/ForeachWithProgressParallelStream.kt
- plugins/diagram-timeline/build.gradle.kts
- plugins/diagram-timeline/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/diagramtimeline/TimelineViewModel.kt
- plugins/files-viewer/src/desktopMain/kotlin/com/alekso/dltstudio/plugins/filesviewer/FilesViewModel.kt
- settings.gradle.kts
Utility module with functions for logs extraction
> Extraction module

- ui-components/src/desktopMain/kotlin/com/alekso/dltstudio/uicomponents/dialogs/FileDialog.kt
JFileChooser is a blocking call that freezes the UI thread when used directly inside a Composable, leading to unresponsiveness and a fatal IllegalStateException on Linux. This fix resolves the crash by using LaunchedEffect to safely launch the file dialog on a background I/O thread. This keeps the main UI thread from blocking and ensures the application remains stable.
> fix(ui): Prevent freeze when opening file dialog

- .github/workflows/gradle-publish.yml
- desktop-app/build.gradle.kts
ci: add GitHub Actions workflow to build and publish release binaries
> ci: add GitHub Actions workflow to build and publish release binaries

- ui-components/src/desktopMain/kotlin/com/alekso/dltstudio/uicomponents/CustomDropDownButton.kt
> CustomDropDownButton style improved
